[package]
name = "tree-friend"
version = "0.1.0"
authors = ["Kyle Baumgarten <BaumDev@proton.me>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.21.0" }
rand="0.8.5"
